export default async function handler(req, res) {
  res.status(200).json([
    {
      name: "Michael",
      age: 31,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Jess",
      age: 30,
      agree: "N",
      address: "서울시 영등포구",
    },
    {
      name: "Remmy",
      age: 1,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Airwrecka",
      age: 23,
      agree: "N",
      address: "서울시 영등포구",
    },
    {
      name: "Michael",
      age: 31,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Jess",
      age: 30,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Remmy",
      age: 1,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Airwrecka",
      age: 23,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Michael",
      age: 31,
      agree: "N",
      address: "서울시 영등포구",
    },
    {
      name: "Jess",
      age: 30,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Remmy",
      age: 1,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Airwrecka",
      age: 23,
      agree: "N",
      address: "서울시 영등포구",
    },
    {
      name: "Michael",
      age: 31,
      agree: "N",
      address: "서울시 영등포구",
    },
    {
      name: "Jess",
      age: 30,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Remmy",
      age: 1,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Airwrecka",
      age: 23,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Michael",
      age: 31,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Jess",
      age: 30,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Remmy",
      age: 1,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Airwrecka",
      age: 23,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Michael",
      age: 31,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Jess",
      age: 30,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Remmy",
      age: 1,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Airwrecka",
      age: 23,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Michael",
      age: 31,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Jess",
      age: 30,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Remmy",
      age: 1,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Airwrecka",
      age: 23,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Michael",
      age: 31,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Jess",
      age: 30,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Remmy",
      age: 1,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Airwrecka",
      age: 23,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Michael",
      age: 31,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Jess",
      age: 30,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Remmy",
      age: 1,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Airwrecka",
      age: 23,
      agree: "Y",
      address: "서울시 영등포구",
    },
    {
      name: "Michael",
      age: 31,
      agree: "Y",
      address: "서울시 영등포구",
    },
  ]);
}
