export const RESPONSIVE_MOBILE_SIZE = 767;
export const USE_TYPE = {
  USER: "USER",
  ADMIN: "ADMIN",
  ADMINSUPER: "ADMINSUPER",
};
export const SEARCH_TYPE = {
  INPUT: "INPUT",
  SELECT_FLAG: "SELECT_FLAG",
  SELECT_BRAND: "SELECT_BRAND",
  SELECT_MAPPING: "SELECT_MAPPING",
};
export const TABLE_COLUMN_TYPE = {
  NUMBER: "NUMBER",
  AUTHORITY: "AUTHORITY",
  USEFLAG: "USEFLAG",
  ADDRESS: "ADDRESS",
};

export const SEARCH_ADDRESS = {
  SIDO: "SIDO",
  SIGOON: "SIGOON",
};
