export const RESPONSIVE_MOBILE_SIZE = 767;
export const USE_TYPE = {
  USER: "USER",
  ADMIN: "ADMIN",
};
export const SEARCH_TYPE = {
  INPUT: "INPUT",
  SELECT_FLAG: "SELECT_FLAG",
  SELECT_BRAND: "SELECT_BRAND",
};
export const TABLE_COLUMN_TYPE = {
  NUMBER: "NUMBER",
  AUTHORITY: "AUTHORITY",
  USEFLAG: "USEFLAG",
  ADDRESS: "ADDRESS",
};
